version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db  

  db:
    image: mysql:8.0 
    environment:
      MYSQL_ROOT_PASSWORD: 1238425wky22  
      MYSQL_DATABASE: leadsearch 
      MYSQL_USER: gabriel 
      MYSQL_PASSWORD: 123123w  
    ports:
      - "3306:3306" 
    volumes:
      - mysql-data:/var/lib/mysql  

volumes:
  mysql-data:
